---
# tasks file for roles/db-tier
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"
# test postgresql Initialization
- name: Check database initialization
  command: postgresql-check-db-dir  /var/lib/pgsql/data
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes

- name: initilize postgres
  shell: postgresql-setup initdb
  shell: chkconfig postgresql on
  when: check_db_output.rc != 0

- name: start postgres
  service:
    name: postgresql.service
    state: started
